import { Inter } from 'next/font/google'
import './globals.css'
import SideNavType from './ui/sideNavs/SideNavType'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Home page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{
        margin: "0",
        padding: "0",
        height: "100vh",
        display: "flex",
        boxSizing: "border-box",
        overflowY: "hidden"
      }}>
        <div className='hidden h-screen  lg:block sticky top-0 bg-slate-800'><SideNavType/></div>
        {children}
      </body>
    </html>
  )
}
