import { Inter } from 'next/font/google'
import './globals.css'
import SideNav from './ui/dashbaord/SideNav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Home page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{
        margin: "0",
        padding: "0",
        minHeight: "100vh",
        height: "100%",
        display: "flex",
        boxSizing: "border-box",
        gap: "24px",
      }}>
        <div className='hidden min-h-full lg:block sticky top-0 bg-slate-800'><SideNav/></div>
        {children}
      </body>
    </html>
  )
}
